# -----------------------------------------------------
# General window layout and colors
# name: "Glow" (halo alrededor de la ventana activa, en vez de solo un cambio de opacidad)
# -----------------------------------------------------

general {
    gaps_in = 10
    gaps_out = 20
    border_size = 3
    col.active_border = $primary $on_primary_container 45deg
    col.inactive_border = rgba(00000000)
    layout = dwindle
    resize_on_border = true
}
